import { events } from 'events.js';
import { forms } from 'forms.js';
import { Project } from 'project.js';
import { projects } from 'projects.js';
import { Task } from 'task.js';
import { tasks } from 'tasks.js';
import { navbar } from 'navBar.js';
import { mainContent } from 'mainContent.js';
import { markup } from 'markup.js';